[main]
font=JetBrainsMono Nerd Font:size=12
icons-enabled=no
terminal=foot -e
prompt="❯ "
icon-theme=Papirus-Dark
width=40
lines=10
horizontal-pad=40
vertical-pad=20
inner-pad=8
line-height=22

[colors]
# RRGGBBAA, no leading '#'
# Note - lines ending with # are default values, not customized ones
background=261b17ff
text=e4cbb3ff
prompt=e35b15ff
placeholder=7f849cff #
input=cdd6f4ff #
match=f38ba8ff #
selection=532f28ff
selection-text=e86420ff
selection-match=f38ba8ff #
counter=7f849cff #
border=e35b15ff

[border]
width=2
radius=0