
# Disable spash banner
splash = false

# Set wallpaper
#preload = /home/adam/.config/hypr/mount_fuji.jpg
#wallpaper = Virtual-1, /home/adam/.config/hypr/mount_fuji.jpg

wallpaper {
  monitor = Virtual-1
  path = /home/adam/.config/hypr/ancient_of_days.png
  fit_mode = contain
}
