
# Background
background #261B17

# Font
font_size 11.0
font_family FiraCode Nerd Font Mono

# Text cursor
cursor_shape block
shell_integration no-cursor

# Window
window_padding_width 20

# Colors
color0  #e35b15
color1  #fabc2c
color2  #e04220
color3  #4d772d
color4  #4395a3